%YAML:1.0
#装甲板角度解算-扩展卡尔曼
#Q00 -> 预测量 x ：用于调整对直线模型中 x 轴方向运动属于直线运动的的置信度，一般预测不用调整
#Q11 -> 预测量 x_v ：用于调整 x 轴速度的波动量，减小效果：击打匀速目标不会一会超前一会落后，增大效果：更新速度快，例如变向
#Q22 -> 预测量 y ：用于调整对直线模型中 y 轴方向运动属于直线运动的的置信度，一般预测不用调整
#Q33 -> 预测量 y_v ：用于调整 y 轴速度的波动量，减小效果：击打匀速目标不会一会超前一会落后，增大效果：更新速度快，例如变向；y 轴（pitch）一般不用调整，很容易打中
#Q44 -> 预测量 z ：用于调整对直线模型中 z 轴不变的置信度
#R00 -> 观测量 yaw：固定不动
#R11 -> 观测量 pitch：固定不动
#R22 -> 观测量 distance：用于调整距离的波动大小，一般距离的波动非常大，调成三位数，距离更新快
#预测过程协方差
Q00: 0.1
Q11: 100
Q22: 0.1
Q33: 100
Q44: 0.01
#观测过程协方差
R00: 1
R11: 1
R22: 800

#装甲板角度解算-普通卡尔曼
#init_count_threshold -> 第一帧预测次数
init_count_threshold: 300
#control_freq -> 控制频率
control_freq: 100.0
#target_change_threshold -> 预测权重
target_change_threshold: 0.25
#predict_coe -> 目标切换距离阈值
predict_coe: 2

#大符函数拟合-粒子滤波
#粒子数
num_particle: 400
#过程噪声, 可以增加粒子多样性,提高滤波器鲁棒性,增大后可以提高滤波器响应速度,但也会造成坐标抖动
process_noise: 0.1
#观测噪声, 影响重要性密度函数,会改变粒子权重,增大可以平滑预测值,但也会增大预测延迟
observe_noise: 0.15

#小符转速-普通卡尔曼滤波
#过程噪声
Q: 10
#观测噪声
R: 100





